apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: sooraj
  labels:
    name: multi
spec:
  containers:
  - name: jupiter
    image: nginx
    env:
      - name: type
        value: planet
    ports:
    - containerPort: 80
  - name: europa
    image: busybox
    env: 
      - name: type
        value: moon
    command: ["sleep","4800"]
