apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
  namespace: sooraj
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/data"
