apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sooraj-pvc
  namespace: sooraj
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: "amazonEBS"
  storageClassName: "gp2"
