apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
  namespace: sooraj
  labels:
    name: non-root-pod
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: non-root-pod
    image: redis:7.0-rc1-alpine
    ports:
    - containerPort: 6379
