apiVersion: v1
kind: Service
metadata: 
  name: hr-web-app-service
  namespace: sooraj
spec:
  type: NodePort
  selector:
    app: hr-webapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30082
