apiVersion: v1
kind: Pod
metadata:
  name: super-user-pod
  namespace: sooraj
  labels:
    type: system_time
spec:
  containers:
  - name: superpod
    image: busybox:1.28
    command: ["sleep","4800"]
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
       
