apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: sooraj
  labels:
    app: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:1.16
        ports:
        - containerPort: 80
